//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.03 at 09:48:26 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://ign4ci0.com/spring/boot/web/service/model", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.ign4ci0.spring.boot.web.service.model;
